name: Deploy to YC

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: yc-install
        # You may pin to the exact commit or the version.
        uses: lxhan/yc-install@v3
        with:
          # Yandex cloud service account private key. No logging in if parameter is not provided.
          SA_KEY: ${{ secrets.YC_KEY }}
    
      - name: Build and push
        env:
           CR_REGISTRY: crptmggr57u83nkgda0h
           CR_REPOSITORY: cd-demo-ys-serverless
           IMAGE_TAG: ${{ github.sha }}
        run: |
          yc container registry configure-docker
          # Билд и пуш
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG   
        
      - name: YC Serverless Container Deploy
        uses: yc-actions/yc-sls-container-deploy@v5.0.0
        env:
           CR_REGISTRY: crptmggr57u83nkgda0h
           CR_REPOSITORY: cd-demo-ys-serverless
           IMAGE_TAG: ${{ github.sha }}
        with:
          yc-sa-id: aje9ah0dukkv9sgbmqti
          container-name: pet-demo-ci-example
          folder-id: b1gjsnkava2p5l65d769
          public: true
          # Url of the docker image
          revision-image-url: cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
